build:
  maxIssues: -1
  excludeCorrectable: false
  weights:

config:
  validation: true
  warningsAsErrors: false

complexity:
  LongMethod:
    active: false
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false
  ComplexInterface:
    active: false

style:
  MagicNumber:
    active: false
  MaxLineLength:
    maxLineLength: 140
  ReturnCount:
    max: 5
  WildcardImport:
    active: false
  FunctionOnlyReturningConstant:
    active: false

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9_]*'
    propertyPattern: '[A-Za-z][A-Za-z0-9_]*'
  VariableNaming:
    privateVariablePattern: '_?[a-z][A-Za-z0-9]*'

exceptions:
  TooGenericExceptionCaught:
    active: false
